### ISSUE TITLE
Load VGM Data from memory instead of a file

### ISSUE THREAD

**Issue by wbb1977** [vgmrips/vgmplay#13]
Hello

This is not a real issuse more a request for a needed function.

Thanks for this great library. Is there a chance that you add a function to load a VGM file from memory. Most other playback libraries offer such a thing and it is great help for a front end app. This helps with loading VGM from zipfiles. 

Of course, I dont know how difficult this would be to realize but can you consider it?

Best regards
Bastian

**Comment by ValleyBell** [comment]
I completely forgot about loading from RAM when writing the VGM loader.
As VGMPlay works currently, that would require an additional full copy of the loading function, modified to use RAM. (It passes a gzFile to a lot of functions.)

I'm (slowly) working on a rewrite of VGMPlay, so I'd like to leave it as it is for now.

**Comment by ValleyBell** [comment]
https://github.com/ValleyBell/libvgm allows you to load and play VGMs from RAM.

player.cpp even contains example code for that. (search for `MemoryLoader`)
