### ISSUE TITLE
Popping/Aliasing distortion in some CPS-2 games

### ISSUE THREAD

**Issue by sergiobenrocha2** [vgmrips/vgmplay#19]
I can hear some clipping distortion in some CPS-2 musics, like in 07 Ken Stage I of Super Street Fighter II

If I increase the 12.5 kHz and decrease other frequencies in Audacity, I can hear a 11 kHz noise almost all the time, following one instrument I think. The sample rating is 11025 Hz, so there's no way to this 11 kHz signal appears, unless it's coming from the harmonics generated by the clipping.

I can't hear this distortion in GME. The samples seems to be good, I opened the files of ssf2 in the Audacity, raw data, Signed 16-bit PCM, big-endian, 1 channel, 11025 Hz.

**Comment by sergiobenrocha2** [comment]
GME spectrum, note that at 11 kHz it's below -72 dB:
![gme spectrum](https://cloud.githubusercontent.com/assets/5431285/11429656/4446a10a-9462-11e5-99e1-fd5c15f3cdaa.png)

For vgmplay, 11 kHz is -60 dB:
![vgmplay spectrum](https://cloud.githubusercontent.com/assets/5431285/11429662/4f8068da-9462-11e5-8fa2-a12542205e29.png)

The samples:
![samples spectrum](https://cloud.githubusercontent.com/assets/5431285/11429675/54b70a02-9462-11e5-8693-62b462d4522d.png)

**Comment by sergiobenrocha2** [comment]
Just a side note, in the channel 2 (guitar) these high freq poppings/aliasing does not appear in low freq tones. It's not happening in the channel 1 too (bass).

**Comment by superctr** [comment]
Seems like the samples are bad in the song itself. Not a VGMPlay issue.

GME apparently adds some extra filtering to the QSound audio output. As VGMPlay's cores are ripped straight from MAME, that is currently outside the scope for VGMPlay's emulation.

**Comment by sergiobenrocha2** [comment]
side note: <ValleyBell> for reference: The native QSound sample rate in SSF2 is 24096 Hz.

**Comment by apollolux** [comment]
"If I increase the 12.5 kHz and decrease other frequencies in Audacity, I can hear a 11 kHz noise almost all the time, following one instrument I think."

For future reference, please only report on audio without EQ applied to it, as obviously if you increase around one frequency you'll hear clipping around that frequency.
