### ISSUE TITLE
vgm2pcm vgm2wav install rm

### ISSUE THREAD

**Issue by leiptrstormr** [vgmrips/vgmplay#24]
Can you add install and rm rules in the Makefile for vgm2pcm and vgm2wav?

**Comment by ValleyBell** [comment]
I don't really work on VGMPlay anymore (just rarely doing bugfixes), because I'm working on a [rewrite](https://github.com/ValleyBell/libvgm) of it, but I'll gladly accept pull requests.

**Comment by vampirefrog** [comment]
@leiptrstormr I've added those to the Makefile, please verify. Marking this as closed.
