### ISSUE TITLE
New Stable Release, Maybes?

### ISSUE THREAD

**Issue by leycec** [vgmrips/vgmplay#26]
@ValleyBell, would issuing a new stable release be feasible at some point? More than a year has passed since the last stable release (**0.40.7**). A significant number of commits have been pushed in the interim... and some of those commits are probably awesome. 🎵🎼🎵🎼🎵     

If not, no biggie. I suspect you're probably devoting the majority of your attention to [`libvgm`](https://github.com/ValleyBell/libvgm), which would make absolute sense. A portable shared library *is* the next giant leap for Linux and macOS VGM junkies. I'd sacrifice video game babies to the first GitHubber to author a `libvgm` plugin for [Music Player Daemon (MPD)](https://www.musicpd.org), my preferred audio player backend. <sup>It is special.</sup>

Relatedly, I maintain a [downstream Gentoo Linux package](https://github.com/leycec/raiagent/tree/master/media-sound/vgmplay) for VGMPlay. Installation reduces to:

* Add [raiagent](https://github.com/leycec/raiagent), my third-party overlay.

        layman -a raiagent

* Unmask the most recent stable release of `vgmplay`.

        echo '>=media-sound/vgmplay-0.40.7' >> /etc/portage/package.accept_keywords

* Install `vgmplay`.

        emerge vgmplay

Three raucous cheers for ongoing VGM goodness!

**Comment by ValleyBell** [comment]
Thanks for the reminder. I added the release for 0.40.8, which I released on the vgmrips.net forum a few months ago.

Also thanks for doing a Gentoo package! I'll try this soon.
