### ISSUE TITLE
(Linux x86_64) "No OPL Chip detected!" but I have one.

### ISSUE THREAD

**Issue by KynikossDragonn** [vgmrips/vgmplay#39]
I've been wanting to try out the "hardware FM" access vgmplay has under Linux but it keeps telling me "No OPL Chip detected!" even though I have one...

It's not a _true_ CMI8738, it's a cheap Chinese made clone (but the actual CMI8738 chip appears to be real) that operates on a card around the size of a credit card and on the PCI Express 1x slot via a bridge chip.

The OPL3 works fine via ALSA MIDI playback:
```
$ aplaymidi -l
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
 16:0    C-Media CMI8738                  C-Media CMI8738 MIDI
 17:0    OPL3 FM synth                    OPL3 FM Port
```

```
$ cat /proc/asound/hwdep 
00-00: OPL3 FM
```

```
$ cat /sys/module/snd_cmipci/parameters/fm_port 
904,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
```
904 is decimal for 0x388

The following is a snippet of `$ cat /proc/ioports`
```
0cf8-0cff : PCI conf1
0d00-ffff : PCI Bus 0000:00
  c000-cfff : PCI Bus 0000:06
    c000-c0ff : 0000:06:00.0
      c000-c0ff : r8169
  d000-dfff : PCI Bus 0000:03
    d000-dfff : PCI Bus 0000:04
      d000-d0ff : 0000:04:00.0
        d000-d0ff : CMI8738-MC6
      d100-d13f : 0000:04:00.1
  e000-efff : PCI Bus 0000:01
    e000-e0ff : 0000:01:00.0
```
And a snippet of lspci -v
```
04:00.0 Multimedia audio controller: C-Media Electronics Inc CMI8738/CMI8768 PCI
 Audio (rev 10)
        Subsystem: C-Media Electronics Inc CMI8738/C3DX PCI Audio Device
        Flags: bus master, stepping, medium devsel, latency 32, IRQ 34
        I/O ports at d000 [size=256]
        Capabilities: [c0] Power Management version 2
        Kernel driver in use: snd_cmipci

04:00.1 Communication controller: C-Media Electronics Inc CM8738 (rev 20)
        Subsystem: C-Media Electronics Inc CM8738
        Flags: medium devsel, IRQ 10
        I/O ports at d100 [size=64]
        Capabilities: [40] Power Management version 2
```

I've tried setting `FMPort=` to "0x388" and "0xD388" yet it fails. Am I doing something wrong? Is the ALSA MIDI getting in the way even though nothing is communicating to it?

**Comment by superctr** [comment]
VGMPlay OPL support has only been tested with real Yamaha OPL chips. It's
possible your chinese clone just isn't detected as a real OPL chip (the
detection function writes certain data and then reads the status register)

**Comment by KynikossDragonn** [comment]
So would the code have to be altered to work with CMI's OPL?

I'm also wondering, has anyone successfully used this when ALSA is exposing the OPL3 as a MIDI device? Because I would think the two would conflict with one another...

**Comment by tatokis** [comment]
Might sound silly, but are you running vgmplay as root?

**Comment by superctr** [comment]
Try  cat /proc/ioports | grep CMIPCI

**Comment by tatokis** [comment]
To add something more, the relevant entry from my vgmplay.ini is
```
; --- FM Hardware Section Start ---
; Hardware FM Port (in hex, usually 220 or 388)
FMPort = 388
; Force FM Mode, even if only the SN76496 is used, also enables Mixed Mode (Hardware FM + Software Emulator)
FMForce = True
; Makes some FM-Voices fading on track-end instead of instant silencing them
FMSoftStop = True
; Overrides Volume setting, if FM hardware is used
; Possible values:
;       = 0 - don't override (default)
;       > 0 - override Volume setting and VGM Volume Modifier
;       < 0 - multiply with volume
FMVolume = 1.0
; --- FM Hardware Section End ---
```
Also make sure vgmplay is loading the right ini with your port. You can check that in a hacky way with `strace -e open vgmplay 2>&1 | grep ini`

And some relevant things to compare with a working setup if needed
```
00:0c.0 Multimedia audio controller: Yamaha Corporation YMF-744B [DS-1S Audio Controller] (rev 02)
	Subsystem: Toshiba America Info Systems YMF-744B [DS-1S Audio Controller]
	Flags: bus master, medium devsel, latency 64, IRQ 11
	Memory at efff8000 (32-bit, non-prefetchable) [size=32K]
	I/O ports at ff00 [size=64]
	I/O ports at fefc [size=4]
	Capabilities: [50] Power Management version 1
	Kernel driver in use: snd_ymfpci
	Kernel modules: snd_ymfpci
```
```
root@nightopia:~# cat /proc/ioports | grep 388
0388-038b : YMFPCI OPL3
```
```
root@nightopia:~# cat /sys/module/snd_ymfpci/parameters/fm_port
904,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
```

**Comment by nukeykt** [comment]
Legacy 0x388 port does not work through PCI express, so you have to use FM port on card's PCI range. As far i remember FM port address was PCI port + 0x50 (e.g 0xd050 for your setup).

**Comment by tatokis** [comment]
I suspect that if 0x388 didn't work due to the bridge, then alsa midi opl playback wouldn't work either.

**Comment by KynikossDragonn** [comment]
**YES**

What NukeyKT said worked! I guess I learn something new every day.

I guess I'll close this issue. I also assume I will have to keep this in mind if I want to try Chocolate Doom's hardware OPL support.

I also have no idea what people say about the CMI's OPL, it doesn't sound "wrong" so far...

**Comment by sofakng** [comment]
Sorry for replying to an old issue, but what card was used for this?  I'm interested in finding a modern audio card with OPL3 support and something that fits into a PCIe x1 slot sounds very interesting!

**Comment by vampirefrog** [comment]
USB is more likely
