### ISSUE TITLE
Our current Makefile is not sensitive to changes in header files

### ISSUE THREAD

**Issue by felipesanches** [vgmrips/vgmplay#4]
I modified a header file and make thinks there's nothing to be done.
We should add a makefile rule to make *.o files dependant on their respective .c and .h files (not only .c files as we have now).

I tried that with the following rule:
$(OBJ)/%.o: $(SRC)/%.c  $(SRC)/%.h

But then the build fails because VGMPlay_AddFmts.c does not have a corresponding VGMPlay_AddFmts.h file. Maybe we should create this header file just to keep the Makefile simple ?

**Comment by ValleyBell** [comment]
This version of VGMPlay is now effectively dead.

vgmplay-libvgm uses CMake as build system, which considers changed header files.
