### ISSUE TITLE
VS 2017 Compile Error

### ISSUE THREAD

**Issue by Cyndanera** [vgmrips/vgmplay#44]
1>------ Build started: Project: VGMPlay, Configuration: Debug Win32 ------
1>ChipMapper.c
1>2151intf.c
1>2203intf.c
1>2413intf.c
1>2608intf.c
1>2610intf.c
1>2612intf.c
1>262intf.c
1>3526intf.c
1>3812intf.c
1>8950intf.c
1>adlibemu_opl2.c
1>adlibemu_opl3.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\opl.c(1276): warning C4018: '<': signed/unsigned mismatch (compiling source file chips\adlibemu_opl2.c)
1>ay8910.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\opl.c(1276): warning C4018: '<': signed/unsigned mismatch (compiling source file chips\adlibemu_opl3.c)
1>ay8910_opl.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ay8910.c(446): warning C4244: '=': conversion from 'double' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ay8910.c(451): warning C4244: '=': conversion from 'double' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ay8910.c(492): warning C4244: '=': conversion from 'double' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ay8910.c(497): warning C4244: '=': conversion from 'double' to 'INT32', possible loss of data
1>ay_intf.c
1>c140.c
1>c352.c
1>c6280.c
1>c6280intf.c
1>dac_control.c
1>emu2149.c
1>emu2413.c
1>es5503.c
1>es5506.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\es5506.c(591): warning C4018: '>': signed/unsigned mismatch
1>fm.c
1>fm2612.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\es5506.c(703): warning C4018: '>': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\es5506.c(807): warning C4018: '>': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\es5506.c(870): warning C4013: 'printf' undefined; assuming extern returning int
1>fmopl.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\fm.c(1763): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\fm.c(1798): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\fmopl.c(356): warning C4244: 'initializing': conversion from 'double' to 'const UINT32', possible loss of data
1>gb.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\fmopl.c(523): warning C4244: 'initializing': conversion from 'double' to 'const UINT8', possible loss of data
1>iremga20.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\fmopl.c(850): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\fmopl.c(1399): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\fmopl.c(1402): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\fmopl.c(1407): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\fmopl.c(1409): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\gb.c(1197): warning C4018: '<': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\iremga20.c(220): warning C4013: 'printf' undefined; assuming extern returning int
1>k051649.c
1>k053260.c
1>k054539.c
1>multipcm.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\k053260.c(324): warning C4018: '>': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\k053260.c(332): warning C4018: '>': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(323): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(367): warning C4244: '=': conversion from 'float' to 'unsigned int', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(562): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(578): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(580): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(597): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(599): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(608): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(610): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(634): warning C4244: '=': conversion from 'const double' to 'unsigned int', possible loss of data
1>nes_apu.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(635): warning C4244: '=': conversion from 'const double' to 'unsigned int', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(643): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(645): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(651): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(626): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\multipcm.c(650): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
1>nes_intf.c
1>np_nes_apu.c
1>np_nes_dmc.c
1>np_nes_fds.c
1>okim6258.c
1>okim6295.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\okim6258.c(118): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
1>Ootake_PSG.c
1>panning.c
1>pokey.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\pokey.c(550): warning C4018: '<': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\pokey.c(1278): warning C4018: '<': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\pokey.c(1314): warning C4018: '<': signed/unsigned mismatch
1>pwm.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\pokey.c(1342): warning C4018: '<': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\pokey.c(1379): warning C4018: '<': signed/unsigned mismatch
1>qsound_ctr.c
1>qsound_intf.c
1>qsound_mame.c
1>rf5c68.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\qsound_ctr.c(227): warning C4018: '<': signed/unsigned mismatch
1>saa1099.c
1>scd_pcm.c
1>scsp.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\saa1099.c(456): warning C4013: 'printf' undefined; assuming extern returning int
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\scsplfo.c(141): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data (compiling source file chips\scsp.c)
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\scsp.c(609): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\scsp.c(618): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\scsp.c(632): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\scsp.c(1077): warning C4013: 'printf' undefined; assuming extern returning int
1>scspdsp.c
1>segapcm.c
1>sn76489.c
1>sn76496.c
1>sn76496_opl.c
1>sn764intf.c
1>upd7759.c
1>vsu.c
1>ws_audio.c
1>x1_010.c
1>ym2151.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\x1_010.c(163): warning C4013: 'printf' undefined; assuming extern returning int
1>ym2413.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(575): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(684): warning C4244: '=': conversion from 'double' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(712): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(724): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(734): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(736): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>ym2413hd.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(1544): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(1546): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(2079): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2151.c(2404): warning C4101: 'chn': unreferenced local variable
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2413.c(286): warning C4244: 'initializing': conversion from 'double' to 'const UINT32', possible loss of data
1>ym2413_opl.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2413.c(453): warning C4244: 'initializing': conversion from 'double' to 'const UINT8', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2413.c(723): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2413.c(1393): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2413.c(1396): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2413.c(1401): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ym2413.c(1404): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>ym2612.c
1>ym3438.c
1>ymdeltat.c
1>ymf262.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf262.c(300): warning C4244: 'initializing': conversion from 'double' to 'const UINT32', possible loss of data
1>ymf271.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf262.c(467): warning C4244: 'initializing': conversion from 'double' to 'const UINT8', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf262.c(730): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf262.c(1363): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf262.c(1366): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf262.c(1371): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf262.c(1373): warning C4244: '=': conversion from 'double' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf262.c(1711): warning C4013: 'printf' undefined; assuming extern returning int
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf262.c(2563): warning C4101: 'chn': unreferenced local variable
1>ymf278b.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(519): warning C4244: 'function': conversion from 'double' to 'int', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(563): warning C4244: '=': conversion from 'INT64' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(612): warning C4244: 'function': conversion from 'UINT64' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(618): warning C4244: 'function': conversion from 'UINT64' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(620): warning C4244: 'function': conversion from 'UINT64' to 'UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(636): warning C4244: '+=': conversion from 'INT64' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(637): warning C4244: '+=': conversion from 'INT64' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(924): warning C4244: '+=': conversion from 'INT64' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(928): warning C4244: '+=': conversion from 'INT64' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(989): warning C4244: '+=': conversion from 'INT64' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(991): warning C4244: '+=': conversion from 'INT64' to 'INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(1100): warning C4244: '+=': conversion from 'INT64' to 'INT32', possible loss of data
1>ymz280b.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf271.c(1103): warning C4244: '+=': conversion from 'INT64' to 'INT32', possible loss of data
1>pt_ioctl.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf278b.c(202): warning C4244: 'initializing': conversion from 'double' to 'const UINT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf278b.c(280): warning C4244: 'initializing': conversion from 'double' to 'const INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf278b.c(288): warning C4244: 'initializing': conversion from 'double' to 'const INT32', possible loss of data
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf278b.c(449): warning C4018: '>': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf278b.c(469): warning C4018: '>': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf278b.c(492): warning C4018: '>': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf278b.c(648): warning C4018: '<': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymf278b.c(669): warning C4018: '<': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(380): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(425): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(435): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(491): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(517): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(522): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(580): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(606): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(611): warning C4018: '>=': signed/unsigned mismatch
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\chips\ymz280b.c(729): warning C4018: '<': signed/unsigned mismatch
1>Stream.c
1>VGMPlay.c
1>VGMPlayUI.c
1>VGMPlay_AddFmts.c
1>g:\work\dev\cyndanera\win32\games\paradise resort\project\vs\vgmplay\vgmplayui.c(716): warning C4996: 'GetVersionExA': was declared deprecated
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\um\sysinfoapi.h(378): note: see declaration of 'GetVersionExA'
1>zlibd.lib(gzlib.obj) : error LNK2019: unresolved external symbol __imp___snprintf referenced in function _gz_open
1>zlibd.lib(gzwrite.obj) : error LNK2019: unresolved external symbol __imp___vsnprintf referenced in function _gzvprintf
1>G:\work\dev\cyndanera\win32\games\Paradise Resort\project\vs\VGMPlay\Debug_Win32\VGMPlay.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "VGMPlay.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by superctr** [comment]
You're missing zlib. Look up instructions for installing zlib headers and
libraries.

Den tis 17 juli 2018 12:48Cyndanera <notifications@github.com> skrev:

**Comment by superctr** [comment]
More accurately, the version you're linking with is out of date.

Den tis 17 juli 2018 12:54Ian Karlsson <themvrules@gmail.com> skrev:

**Comment by Cyndanera** [comment]
So how do I update the lib?

**Comment by superctr** [comment]
https://stackoverflow.com/questions/49505546/how-to-use-zlib-library-in-visual-studio-2017

Den tis 17 juli 2018 13:42Cyndanera <notifications@github.com> skrev:

**Comment by ValleyBell** [comment]
The version of zlib (zdll.lib / zlib.lib / zlibd.lib) that comes with VGMPlay was compiled using Visual C++ 6.0. I was able to successfully link the static libs when compiling with VS 2010, but compatibility eventually broke somewhere between 2010 and 2015.

Your only chance is to compile zlib by yourself. (or link against zdll.lib, which I do in Release mode, because linking against zlib1.dll still works)

**Comment by westonlast** [comment]
Speaking of Release mode, when do you think would be a good time to release the latest version of "in_vgm?"  That "nuked" core seems like a pretty big deal, and I think it's been committed without release for almost a year.

**Comment by superctr** [comment]
well, not now because it doesn't even compile.

**Comment by Cyndanera** [comment]
it compiles if you replace the old zlib with the new zlib build And what is the main source file that has int main() function?

**Comment by superctr** [comment]
```
$ grep -rn "int main"                                   
VGMPlay/vgm2pcm.c:72:int main(int argc, char *argv[]) { 
VGMPlay/vgm2wav.c:94:int main(int argc, char *argv[]) { 
VGMPlay/VGMPlayUI.c:69:int main(int argc, char* argv[]);
VGMPlay/VGMPlayUI.c:254:int main(int argc, char* argv[])
```

**Comment by ValleyBell** [comment]
The problem was solved, so I'll close this issue.
