### ISSUE TITLE
VGMPlay as a GStreamer Element / Plugin

### ISSUE THREAD

**Issue by TheYokai** [vgmrips/vgmplay#45]
I asked about this on the website vgmrips, but thought it might also be worth trying to ask this here.

I worked on a patch for clementine recently that added VGM playback support ( clementine-player/Clementine#6089 ) but unfortunately GStreamer currently does not support VGM to the degree that VGMplay does due to using an out of date version of libgme. I looked into alternative solutions such as updating GME to @kode54 s standard (see wyatt8740/Game_Music_Emu#5 ) but it wouldn't solve some underlying issues with GME as a Gstreamer element (unable to playback VGZ format, currently supports formats like NSF which are unsafe / unreliable, doesn't fit Gstreamers pipeline approach.)

To put it bluntly, I'm trying to look into alternative solutions for VGM playback with Gstreamer. This would not only improve clementine player but could also give QT or any Gstreamer application the ability to accurately playback VGM/VGZ files. Would it be within the scope of VGMplay to provide an option to build a gstreamer plugin for VGM files in the same way Winamp is included with the compile tools?

**Comment by superctr** [comment]
There won't be a GStreamer plugin for vgmplay due to some fairly extensive code rewrite that would be required to run it as a gstreamer plugin. For example, we can't have any global variables to store the player state, as gstreamer can play multiple instances simultaneously with the same code. libvgm could have one in the future, though

**Comment by ValleyBell** [comment]
A libvgm-based GStreamer plugin would definitely be something I'd like to have.

**Comment by TheYokai** [comment]
Thanks for taking the time to respond @superctr . I would be interested in contributing in whatever way I can to libvgm getting gstreamer support!
