### ISSUE TITLE
Phantasy Star II SSG-EG or whatever issue

### ISSUE THREAD

**Issue by westonlast** [vgmrips/vgmplay#48]
The SSG-EG stuff is used heavily in Phantasy Star II, especially at the title screen.  This sounds wrong in "in_vgm."  At least, I think it does, because I'm not able to find a hardware recording.  This is how I think it's supposed to sound:

https://www.youtube.com/watch?v=24JW1lxW-2U (Correct)

This is more like how "in_vgm" sounds:

https://www.youtube.com/watch?v=zi2RuDRTIWI (Incorrect)

Notice the weird oscillations in the second video when the background pad changes?  Is this an issue with the imperfection of the VGM logging format, is something wrong with "nuked," or is the second video really how it sounded on hardware?

**Comment by ValleyBell** [comment]
Here is a video from the "Phantasy Star Collection" CD that was released in 1993.
https://www.youtube.com/watch?v=aDYlnt-nGac&t=14m7s

The recording is from real hardware, so it confirms that in_vgm is correct.

**Comment by westonlast** [comment]
That's the Japanese version, though.  Notice the loud percussion.  The English version is the one I'm concerned about, which has quiet percussion.

I just checked in Genesis Plus GX with the English Phantasy Star II ROM:  This oscillation artifact isn't there, with both the MAME and nuked sound cores.

**Comment by superctr** [comment]
Ok, did some checking and the problem appears to be the SSG-EG indeed, but it appears to be an error in the VGM file itself. 0xFF is written to the channel 4 SSG-EG register for some reason.

**Comment by westonlast** [comment]
Very interesting.  Do you have a relatively quick and easy way to scan the Phantasy Star II VGMs and always set the SSG-EG to zero?

**Comment by westonlast** [comment]
I've updated the Phantasy Star II (English) set: https://mega.nz/#!TcwSxKjb!eEmjs0C422KrhYtxWQwLeDycQhynTTcwFkEfKXWDqh8
