### ISSUE TITLE
Add more command-line options to vgmplay

### ISSUE THREAD

**Issue by vampirefrog** [vgmrips/vgmplay#5]
I find myself needing to specify the number of loops and the fade-out time directly on the command-line. This could be accomplished either by implementing a couple of options for that, or just an option to specify the ini file. Ideally, both.

**Comment by ValleyBell** [comment]
https://github.com/ValleyBell/vgmplay-libvgm has a `--config Section.Field=value` option that lets you override everything that it set by the .ini file.
