### ISSUE TITLE
Feature Request: display of currently used "Emulator Type" in UI while playing

### ISSUE THREAD

**Issue by funky327** [vgmrips/vgmplay#52]
Feature Request: display of currently used "Emulator type" in UI while playing. There is no indicator as to which core/emulator type you are using.

I'd suggest something like the following, "Emulator type" being the added info:

```
VGM Player
----------

Playlist File:  Sword of Vermilion.m3u
Playlist Entry: 6 / 33
File Name:      06 - Village A.vgz

Track Title:    Village A
Game Name:      Sword of Vermilion
System:         Sega Mega Drive / Genesis
Composer:       Hiroshi Kawaguchi
Release:        1989/12/16
Version:        1.50      Gain: 1.00    Loop: Yes (00:43.89)
VGM by:         Matthew Dickinson
Notes:

Used chips:     SEGA PSG, YM2612
Emulator type:  Nuked OPN2

Playing 2.54%   00:01.04 / 00:43.89 seconds
```

**Comment by superctr** [comment]
I think we will consider this for the vgmplay rewrite. Currently the emulator core name is hardcoded in in_vgm and not present at all in the vgmplay code (we use IDs instead there).

**Comment by ValleyBell** [comment]
Solved in vgmplay-libvgm: https://github.com/ValleyBell/vgmplay-libvgm/commit/873f6c99e73bdf40bb256a94c186fb08b8709656
