### ISSUE TITLE
Feature Request: Enhanced PSG mode from Dega emulator (Sega Master System, SN76489)

### ISSUE THREAD

**Issue by Corak667** [vgmrips/vgmplay#58]
Hi, there is a great emulator called Dega, it has nice feature of Enhanced PSG mode (sounds much better than original)
I wanted somehow to add this feature to VGMPlay, as experimental optional workaround for Sega Master System SN76489 PSG chip.
dega src: https://github.com/Plombo/dega
Feature there:
https://github.com/Plombo/dega/blob/master/mast/dpsg.cpp

**Comment by Corak667** [comment]
dega Binary: http://coraksoft1.narod.ru/emu/sega/emul/Dega.7z

**Comment by superctr** [comment]
The enhanced mode appears to just be some kind of echo / reverb effect. I don't think we will support this, if you use Winamp, FB2K or XMPlay there are built in effects you can use instead.

**Comment by ValleyBell** [comment]
Yeah, it's just a simple echo: https://github.com/Plombo/dega/blob/master/mast/dpsg.cpp#L182-L186 and it's only applied to the first 2 PSG channels. (It doesn't even affect all 4 channels.)  
It has a period/delay of 4096 samples. (about 93 ms at 44.1 KHz sample rate)

I don't see a reason for adding this to VGMPlay.
But feel free to make a fork of VGMPlay that includes the feature.
