### ISSUE TITLE
verify functionality of removed code from GetAccurateChipName

### ISSUE THREAD

**Issue by felipesanches** [vgmrips/vgmplay#6]
Here's the discussion:
https://github.com/vgmrips/vgmplay/commit/da1402669dc30b4fd0c3a617f246cad50fc0a898

And here's the commit removing the unused code:
https://github.com/vgmrips/vgmplay/commit/6739212e2f16d182a7e47a7d81edf53cdc3304f2

**Comment by ValleyBell** [comment]
obsolete with VGMPlay 0.40.6
