### ISSUE TITLE
Nuked OPN2 unexpected sound when plays some tracks

### ISSUE THREAD

**Issue by amrtf** [vgmrips/vgmplay#61]
OS: openSUSE Tumbleweed 20190823

I've discovered a problem when uses Nuked OPN2 (not MAME or Gens) with two tracks of Rocket Knight Adventures (stage 6 and stage 7), tested with log to WAV and playback. It sounds only some sounds from a channel. Also I've discovered that happens with all the tracks of that game.

I attach a ZIP file with the .ini file when I discovered the problem with both files directly from log to WAV. And another ZIP file with the expected sound to output using MAME (log to WAV) as MP3.

[NOPN2.zip](https://github.com/vgmrips/vgmplay/files/3543083/NOPN2.zip)
[Expected sounds.zip](https://github.com/vgmrips/vgmplay/files/3543079/Expected.sounds.zip)

**Comment by superctr** [comment]
It's a known issue. Those VGMs are broken on real hardware too, they have
to be fixed or relogged.

**Comment by amrtf** [comment]
Oh, I didn't even knew that.
Thanks!
