### ISSUE TITLE
.vgm Game Gear rips don't play in Winamp

### ISSUE THREAD

**Issue by Tasosgemah** [vgmrips/vgmplay#78]
Downloaded the latest version of the plugin but the songs don't play in Winamp. They do play in the vgm player but not with the Winamp plugin.

**Comment by ValleyBell** [comment]
Please provide more information:

- which exact plugin version you used
- what VGMs you tried
- what the result was (open error / playing silence / ...)

**Comment by Tasosgemah** [comment]
> 
> 
> Please provide more information:
> 
>     * which exact plugin version you used
> 
>     * what VGMs you tried
> 
>     * what the result was (open error / playing silence / ...)

Version 0.40.9 from the releases section.

I used the Shinobi vgm from this link:
https://www.smspower.org/uploads/Music/GGShinobi-GG.zip

The result is when i drag the files into the playlist i get the duration of each song but when i try to play them, it does nothing (unless there are other different files in the same playlist, so it goes to the next one it can play).

If i drag the files in the VGM player exe, they play fine.

I have a big collection of chip music files and they all play fine with Winamp. But they all have the .vgz extension. These game gear songs have the .vgm extension and for some reason i can't play them.

**Comment by ValleyBell** [comment]
seems to work fine for me:
![in_vgm_w_Winamp_5666](https://user-images.githubusercontent.com/7661755/101683455-3e85dc00-3a65-11eb-91ef-0c746c264538.png)

in_vgm 0.40.9, Unicode build (in_vgm_w.dll) with Winamp 5.666

Do you maybe have another Winamp plugin installed that tries to open VGM files?
The plugin could attempt to open .vgm, but not .vgz.

Does it work if you rename the files from `.vgm` to `.vgz`? This would hint at the "other plugin is handling .vgm" theory, as in_vgm itself ignores the file extension.

**Comment by Tasosgemah** [comment]
Yea, changing the extension to vgz works!

Now i have to find what causes the conflict :(

**Comment by Tasosgemah** [comment]
Btw, this is the window
![Untitled](https://user-images.githubusercontent.com/12124465/101696227-777e7a80-3a7e-11eb-96d7-f27d1483bc5d.png)
 that opens, looks different than yours?

**Comment by ValleyBell** [comment]
looks fine to me

Can you try if the files play in a clean Winamp installation?

**Comment by ValleyBell** [comment]
Please try again with in_vgm 0.50.1.

If it still doesn't work, make an issue in https://github.com/ValleyBell/in_vgm-libvgm.

**Comment by Tasosgemah** [comment]
> 
> 
> Please try again with in_vgm 0.50.1.
> 
> If it still doesn't work, make an issue in https://github.com/ValleyBell/in_vgm-libvgm.

I want to sets this but in the link you posted i can only find the source code. Maybe i'm missing something?

**Comment by ValleyBell** [comment]
You can download current releases on vgmrips, as usual: https://vgmrips.net/forum/viewtopic.php?f=3&t=112

The GitHub Releases page is often a bit behind in that regard.

**Comment by Tasosgemah** [comment]
Ok thanks, i got it.

I still have the same issue though. I have to rename the extension to vgz otherwise they don't play. I never figured out why it does that.
