### ISSUE TITLE
"Error opening sound device!" under Linux

### ISSUE THREAD

**Issue by freq-mod** [vgmrips/vgmplay#80]
Trying to play any VGM file via VGMPlay throws this error. Happens both with OSS and libao.

OS is Arch Linux x64, VGMplay is fresh master.

**Comment by ValleyBell** [comment]
You could try launching vgmplay using the `vgm-player` script, which calls ALSA or PulseAudio wrappers.

---

However I recommend to just build the new libvgm-based VGMPlay version:
https://github.com/ValleyBell/vgmplay-libvgm

There are no compile instructions for it yet, unfortunately.
The basic process is:
- clone the Git repo including the submodule
- build the libvgm library from the `libvgm` subfolder (the default settings should be good)
- then build VGMPlay itself (it should find the libvgm library automatcally)

**Comment by freq-mod** [comment]
I see. I will try that one.

**Comment by freq-mod** [comment]
:thinking: 
`In file included from emu/cores/emu2413.c:18:`
`emu/cores/emutypes.h:19:15: error: conflicting types for ‘int64_t’`
`19 | typedef INT64 int64_t;`
`      |               ^~~~~~~`
`In file included from /usr/include/sys/types.h:155,`
               ` from /usr/include/stdlib.h:394,`
`                 from emu/cores/emu2413.c:14:`
`/usr/include/bits/stdint-intn.h:27:19: note: previous declaration of ‘int64_t’ was here`
`   27 | typedef __int64_t int64_t;`
`      |                   ^~~~~~~`

**Comment by ValleyBell** [comment]
hmm ... are you building the CMake project? CMake should detect the stdint files.
(The Makefile is probably a bit out of date. It is a leftover from the initial development.)

**Comment by freq-mod** [comment]
hmm, I've built that with a makefile (sinple make command).
I can build libvgm with cmake now, but vgmplay itself, errors out:

> CMake Error at CMakeLists.txt:147 (add_executable):
  Target "vgmplay" links to target "libao::libao" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

**Comment by freq-mod** [comment]
ah, nevermind, libvgm `player` works

**Comment by ValleyBell** [comment]
With `player` you unfortunately don't get too many options. (and no DBus support etc)

Regarding libao - that's a known issue.
I already have a PR regarding that: https://github.com/ValleyBell/vgmplay-libvgm/pull/2

(The main reason is an issue of the config/install script on the libvgm side.)
