### ISSUE TITLE
vgm2wav ignores vgmplay.ini

### ISSUE THREAD

**Issue by Schatteneis** [vgmrips/vgmplay#85]
vgm2wav completely ignores vgmplay.ini, it should at least use settings like PlaybackRate.

**Comment by superctr** [comment]
You can use regular vgmplay and set the "LogSound" parameter in the ini to 1 instead (or run with -LogSound:1)

**Comment by ValleyBell** [comment]
vgm2pcm and vgm2wav both don't read any additional configuration.  
I'm also not going to port the INI file reader over to them from VGMPlay.

If you want to log VGMs using a special configuration, you will have to use VGMPlay itself.
