### ISSUE TITLE
About OPL3 Hardware Passthrough

### ISSUE THREAD

**Issue by denjhang** [vgmrips/vgmplay#87]
My computer is Windows 7 32bit and I have a YMF724 sound card installed (the drivers are installed correctly), I want to listen to OPL3 VGM using the hardware passthrough feature.
So I installed porttalk22 and used
`AllowIo /a.` 
At this point, I added the following statements to the ini configuration files of both midiplay and vgmplay
`FMPort=220`
midiplay can correctly identify OPL3 hardware and play midi. (The third line of the console shows that OPL3 is recognized)
However, vgmplay does not seem to use hardware pass-through when playing the vgm of the OPL series, and there is no message similar to OPL3 being recognized, but still uses software simulation (I can see whether it belongs to pass-through by checking the volume change of the Windows mixer .)

**Comment by ValleyBell** [comment]
What version of VGMPlay are you using? (`vgmplay.exe --version`)
And what is the output that VGMPlay shows?

**Comment by denjhang** [comment]
![截图未命名0326010834](https://user-images.githubusercontent.com/61811583/160168997-9997be08-c7fd-43fb-a27e-4108dcfdd50d.jpeg)
![截图未命名0326011028](https://user-images.githubusercontent.com/61811583/160169014-f93b3679-2eba-42ca-b886-dca8d4c257bc.jpeg)
![截图未命名0326010931](https://user-images.githubusercontent.com/61811583/160169018-64447f0e-5187-417e-aca7-5fdae1f78a90.jpeg)
![截图未命名0326010858](https://user-images.githubusercontent.com/61811583/160169023-fbd8360e-e194-485a-acc3-c92fdf7d1437.jpeg)

**Comment by ValleyBell** [comment]
Yeah, sorry - you need VGMPlay v0.40.x for playback on actual OPL hardware.

The feature never made it into v0.50.
