### ISSUE TITLE
[Release Begging] Please release one last stable version. I beg this of you, ValleyBell.

### ISSUE THREAD

**Issue by leycec** [vgmrips/vgmplay#95]
@ValleyBell! Hope you're doing well. What a wild ride Planet Earth has been, eh? `</ahem>`

**So.** I've packaged `vgmplay` for literally *years* on Gentoo Linux at [my indomitable Gentoo overlay](https://github.com/leycec/raiagent). After attempting to reinstall `vgmplay` tonight, I couldn't help but note that:

* You just resuscitated this repository from the dead. VGM Gods be praised! :clinking_glasses: 
* The most recent stable release of `vgmplay` (i.e., `vgmplay 0.40.9`) no longer compiles under modern build toolchains:

```
make -j3 -l1.95 --directory=VGMPlay PREFIX=/usr DESTDIR=/var/tmp/portage/media-sound/vgmplay-0.40.9-r1/image USE_LIBAO=1 DEBUG=0 DISABLE_HWOPL_SUPPORT=0 
make: Entering directory '/var/tmp/portage/media-sound/vgmplay-0.40.9-r1/work/vgmplay-0.40.9/VGMPlay'
Compiling chips/262intf.c ...
Compiling chips/2151intf.c ...
Compiling chips/2203intf.c ...
Compiling chips/2413intf.c ...
Compiling chips/2608intf.c ...
Compiling chips/2610intf.c ...
Compiling chips/2612intf.c ...
Compiling chips/3526intf.c ...
Compiling chips/3812intf.c ...
Compiling chips/8950intf.c ...
Compiling chips/adlibemu_opl2.c ...
Compiling chips/adlibemu_opl3.c ...
Compiling chips/ay8910.c ...
Compiling chips/ay_intf.c ...
Compiling chips/c140.c ...
Compiling chips/c352.c ...
Compiling chips/c6280.c ...
Compiling chips/c6280intf.c ...
Compiling chips/dac_control.c ...
Compiling chips/es5503.c ...
Compiling chips/es5506.c ...
Compiling chips/emu2149.c ...
Compiling chips/emu2413.c ...
Compiling chips/fm2612.c ...
Compiling chips/fm.c ...
Compiling chips/fmopl.c ...
Compiling chips/gb.c ...
Compiling chips/iremga20.c ...
Compiling chips/k051649.c ...
Compiling chips/k053260.c ...
Compiling chips/k054539.c ...
Compiling chips/multipcm.c ...
Compiling chips/nes_apu.c ...
Compiling chips/nes_intf.c ...
Compiling chips/np_nes_apu.c ...
Compiling chips/np_nes_dmc.c ...
Compiling chips/np_nes_fds.c ...
Compiling chips/okim6258.c ...
Compiling chips/okim6295.c ...
Compiling chips/Ootake_PSG.c ...
Compiling chips/panning.c ...
Compiling chips/pokey.c ...
Compiling chips/pwm.c ...
Compiling chips/qsound_ctr.c ...
Compiling chips/qsound_mame.c ...
Compiling chips/qsound_intf.c ...
Compiling chips/rf5c68.c ...
Compiling chips/saa1099.c ...
Compiling chips/segapcm.c ...
Compiling chips/scd_pcm.c ...
Compiling chips/scsp.c ...
Compiling chips/scspdsp.c ...
Compiling chips/sn76489.c ...
Compiling chips/sn76496.c ...
Compiling chips/sn764intf.c ...
Compiling chips/upd7759.c ...
Compiling chips/vsu.c ...
Compiling chips/ws_audio.c ...
Compiling chips/x1_010.c ...
Compiling chips/ym2151.c ...
Compiling chips/ym2413.c ...
Compiling chips/ym2612.c ...
Compiling chips/ym3438.c ...
Compiling chips/ymdeltat.c ...
Compiling chips/ymf262.c ...
Compiling chips/ymf271.c ...
Compiling chips/ymf278b.c ...
Compiling chips/ymz280b.c ...
Compiling chips/ay8910_opl.c ...
Compiling chips/sn76496_opl.c ...
Compiling chips/ym2413hd.c ...
Compiling chips/ym2413_opl.c ...
Compiling VGMPlay.c ...
Compiling VGMPlay_AddFmts.c ...
Compiling Stream.c ...
Compiling ChipMapper.c ...
Compiling VGMPlayUI.c ...
Compiling vgm2pcm.c ...
Compiling vgm2wav.c ...
Linking vgmplay ...
Linking vgm2pcm ...
Linking vgm2wav ...
/usr/libexec/gcc/x86_64-pc-linux-gnu/ld: obj/VGMPlay_AddFmts.o:(.bss+0x4): multiple definition of `VGMEnd'; obj/VGMPlay.o:(.bss+0x2a): first defined here
/usr/libexec/gcc/x86_64-pc-linux-gnu/ld: obj/VGMPlay_AddFmts.o:(.bss+0x4): multiple definition of `VGMEnd'; obj/VGMPlay.o:(.bss+0x2a): first defined here
/usr/libexec/gcc/x86_64-pc-linux-gnu/ld: obj/VGMPlay_AddFmts.o:(.bss+0x4): multiple definition of `VGMEnd'; obj/VGMPlay.o:(.bss+0x2a): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:241: vgmplay] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make: *** [Makefile:246: vgm2pcm] Error 1
collect2: error: ld returned 1 exit status
make: *** [Makefile:251: vgm2wav] Error 1
make: Leaving directory '/var/tmp/portage/media-sound/vgmplay-0.40.9-r1/work/vgmplay-0.40.9/VGMPlay'
```

Fascinatingly, the live version of `vgmplay` pulled from this `git` repository compiles fine. I've reluctantly pulled Gentoo support for `vgmplay 0.40.9` from my overlay. This saddens me.

I suspect you'll probably archive this entire repository in favour of [`vgmplay-libvgm`](https://github.com/ValleyBell/vgmplay-libvgm) at some point. Before that hammer falls, would you mind pushing out one final stable release of `vgmplay` at some point? Release beggars gonna beg. :man_shrugging: 

Oh – and thanks so much for your most recent round of commits here. It's wonderful to see old projects receiving last-minute spit and polish like this. As always, you do the good work that needs doing.

**Comment by cyberic99** [comment]
maybe adding ``-fcommon`` to the CFLAGS would fix it ?
this behavior has changed since gcc 10

**Comment by leycec** [comment]
**Excellent suggestion!** Sadly, my copious well of free time has already run dry. Instead, I shall now heckle, throw peanuts from the gallery, and pray for somebody else to do something. :peanuts:

**Comment by ValleyBell** [comment]
I'll do some compile checks on various systems and try to tag a 0.40.9.1 release within the next week.

In case you want to restore/fix the existing releases, just use the patch from #74, which fixes the linking error:
https://patch-diff.githubusercontent.com/raw/vgmrips/vgmplay/pull/74.patch

---

btw: The state of legacy VGMPlay (= this repo) is effectively "I'm not actively working on it, but PRs are accepted."  
I won't archive this repo unless the new VGMPlay supports hardware OPL again.

**Comment by leycec** [comment]
Superb! Thanks so much for your continued blood, sweat, and code, @ValleyBell. :hugs:

**Comment by ValleyBell** [comment]
Here we go: https://github.com/vgmrips/vgmplay/releases/tag/0.40.9.1
It is not a *true* release with a precompiled player, but the tag should be enough to be able to serve as versioning.

**Comment by leycec** [comment]
**Pure awesome sauce.** Thanks so much for the assist. I now shower you with cosmic blessings that will surely ensure your startling success in both this life and the next. :magic_wand: :star2: :boom:

**Comment by ValleyBell** [comment]
No problem. 🙂
I'm still using your Gentoo overlay, so I have an interest in it being maintained properly as well.
